### ISSUE TITLE
SQL RAW - Text type are not FDT_STRING

### ISSUE THREAD

**Issue by code34** [Torndeco/extDB2#116]
there is an issue with text type (and perhaps other, i dont check) when you do a select

[quote]
sql_raw_v2.cpp

						else
						{
							if (temp_str.empty())
							{
								result += "\"\"";
							}
							else
							{
								result += temp_str;
							}
						}
[/quote]

text type from mysql are returned as variable name instead to be encapsuled with double quote as a string. Anyway, when result is empty you return a sting "";

**Comment by Torndeco** [comment]
MySQL Reports TEXT as FDT_BLOB not as FDT_STRING
Changing the behaviour would break to much 
Also extDB2 default behaviour for null or empty values is to return empty string.

extDB2 doesn't attempt to parse and auto-detect the variables and just plays dumb with data.
Mainly due to the fact that arma str command is so broken that it doesn't escape special characters.

If you need more precise control you should look @ SQL_CUSTOM
It basically allows you to define Prepared Statements in an ini file, plus it is alot more secure.

**Comment by Torndeco** [comment]
Also if you are clever if your makeup of Database Table

You can use varchar for  text inputs  & text for values containing arrays etc
