### ISSUE TITLE
Custom paths for SQL_CUSTOM files

### ISSUE THREAD

**Issue by kkotowick** [Torndeco/extDB2#20]
Currently, files holding prepared statements for the SQL_CUSTOM protocol are loaded from

    Arma 3\extDB\sql_custom\filename.ini

This makes it rather difficult to keep it packaged nicely with the mission file it is associated with. I would like to recommend that support is added for file paths within the mission addon folder (similar to how it uses the extdb-conf.ini file from within the addon folder), to allow for easier packaging and deployment of all mission-relevant files.

**Comment by Torndeco** [comment]
Its a nice bit of work to add code for the ability to read PBO.
If someone shows me a nice implement of PBO code that is cross platform, i will take a look at it.
Also dePBO.dll doesn't count since there is no linux version of dll.

Easier method is add ability to pass the configfile as string to extDB2 i.e via loadfile.
I be meaning to look @ adding it in for awhile

Otherwise i would just add error output
i.e
_result = "extDB2" callExtension "9:ADD_DATABASE_PROTOCOL:................";
if _result != "[1]" then 
{
   diag_log "ERROR MESSAGE ABOUT CHECKING SQL_CUSTOM FILE";
   diag_log _result;
};

**Comment by kkotowick** [comment]
Doesn't it already read the extdb-conf.ini from inside the PBO?

**Comment by Torndeco** [comment]
Nope, extdb-conf.ini locations are either same directory as extension or in arma root directory.
Makes no sense packaging the file in mission / mod files, when it contains database details etc
