### ISSUE TITLE
Opening multiple connections

### ISSUE THREAD

**Issue by dbenson24** [Torndeco/extDB2#31]
It seems like regardless of playercount I'm still getting only 1 connection to the database. Whether I have 5 players or 105 players on the server. Any suggestions? I've got the default settings on in terms of minimum database connections and maximum (1 and 4 respectively).

**Comment by Torndeco** [comment]
extDB2 will only going to create a new Database Connection if there is no free existing Database Connection available, otherwise it will re-use an existing Database Connections

So it is possible to have just one Database Connection that handles all the queries.

--------
I need to update the ini file comments but the minSession / maxSession.

maxSession doesn't have any effect anymore.
minSession is just the min number of sessions to keep active, closes sessions it they been idle to long (idleTime=60).

--------
More than likely your queries are all getting handled by 1 Database Connection.
If it does require a second database connection the odd time, it is getting closed when its be inactive for 60 seconds.

-------

The other thing is [Main] Threads
If you have this set to alow number like 1.
There will only ever be 1 database connection used by worker threads (not connecting SYNC queries).
