### ISSUE TITLE
HTTP Requests

### ISSUE THREAD

**Issue by kavinsky** [Torndeco/extDB2#32]
Make possible to do HTTP requests.

**Comment by Torndeco** [comment]
It can be done, fairly easy
Already doing HTTP Requests for Steam VAC Info

I need an example of what you like todo with the HTTP Requests

**Comment by kavinsky** [comment]
if you can add a whitelist of hosts to it will be awesome too.

**Comment by Torndeco** [comment]
I still need an example of what you like to do with HTTP Requests.
Atm i have no idea how you would like to Handle HTTP i.e sending / receiving / parsing the info received

**Comment by kavinsky** [comment]
Handling could be done like mysql async to not overhead the ArmA server waiting for the response,

also parsing the response its not needed i think.

**Comment by Torndeco** [comment]
You misunderstand 
What are you trying to accomplish via HTTP ?
Why use HTTP Request to begin with etc
Do you want to receive Data via HTTP, is it in some format like JSON / XML etc...

I need you to give me an example / design goal of what you want to accomplish via HTTP.
Otherwise its pointless for to to write a Protocol for extDB2 without a reason for it.

For example i could add FTP support, but it doesn't mean i should.
Since i cant think of a valid reason for extDB2 to use FTP.

**Comment by kavinsky** [comment]
yeah i misundrestand :) sorry.

What i want to accomplish is to make request to a external web api to syncronize multiple servers and add centralize game logic to every server running the mission.

**Comment by Torndeco** [comment]
Public mission or private use ?
You got a timeframe in mind ?

**Comment by kavinsky** [comment]
- public mission
- open to all :D

**Comment by chris579** [comment]
So, clearly you want to do requests to a external server via http to transfer code etc.? Would be interested into something like this too or alternatively a possibility to make a TCPConnection from extDB to another server.

**Comment by kavinsky** [comment]
@chris579 yes, TCPConnection between extDBs would be interesting too.

**Comment by Torndeco** [comment]
@kavinsky Finally have some code that needs some testing etc
If you got Skype give me a shout and can throw you a test build if you interested in helping testing it out.
Mainly i just need some feedback, and i need to test out HTTPS Login etc

Got sidetracked abit update some of the toolchain for building extDB2

-------------------

TCPConnection between servers is doable, but best off to have a seperate application to be inbetween the servers.
That way you could enforce some security, otherwise you run risk of a remote exec script hack running on all connected servers.

**Comment by kavinsky** [comment]
@Torndeco my skype is: kavinskyodd

**Comment by Torndeco** [comment]
Closing this, HTTP_RAW Support is in latest version of extDB2
If anyone has requests or encounters an issue make a seperate issue thanks
