### ISSUE TITLE
SQL_Custom seams broken...

### ISSUE THREAD

**Issue by shukari** [Torndeco/extDB2#42]
9:ADD_DATABASE_PROTOCOL:Database:SQL_RAW:SQL
this command working but with:
9:ADD_DATABASE_PROTOCOL:Database:SQL_CUSTOM:SQL
i get [0,"Failed to Load Protocol"]

I used v50! I have created a folder under @extDB/extDB named "sql_custom" with a file named "sql_custom.ini". But it seams broken.... no log entries....

**Comment by Torndeco** [comment]
I really need to change up the extdb-conf.ini examples

[Log]
;; Flush Logs after each write, more work on Harddrive
Flush = true

This way log entries are flushed to the logfile straight away.
Otherwise logs might not get flushed until server is closed nicely.

--------------

Anyway your issue is you didn't pass along the sql_custom filename. (You don't need to send .ini part).

9:ADD_DATABASE_PROTOCOL:Database:SQL_CUSTOM:SQL:sql_custom

9:ADD_DATABASE_PROTOCOL:Database:SQL_CUSTOM_V2:SQL:sql_custom
Also recommend you use SQL_CUSTOM_V2, it just returns, [1,[]]   instead of [1,[[]] for empty results.


I will update the wiki later, as its missing an example of how to setup SQL_CUSTOM.

**Comment by shukari** [comment]
Thank you i was a little bit anry, because i try it for 6 hours ;D
pls include an example (for sql_cutom) in the release (i mean the folder and a file ;D)

**Comment by Torndeco** [comment]
I look at it but i need to come up with better example file, it doesn't highlight the OUTPUT options

Anyway
extDB2 will create the sql_custom directory for you if its missing :)

Its basically were the extension is located, so its either
@extDB2/extDB/sql_custom/<filename>.ini
or
extDB/sql_custom/<filename>.ini

There is one in https://github.com/Torndeco/extDB2/blob/master/examples/sql_custom/example.ini
Its similar one to what  a3wasteland extDB2 beta branch is using

**Comment by shukari** [comment]
I mean against the confusion ;D

**Comment by shukari** [comment]
A little question what is better the dll in @extDB as mod or in the gameroot at the exe?!?

**Comment by Torndeco** [comment]
It makes no difference, you can put it arma3 root or @extDB2
