### ISSUE TITLE
Adding support for MongoDB

### ISSUE THREAD

**Issue by chris579** [Torndeco/extDB2#52]
It would be really great to add the support for MongoDB especially for Arma, just because of performance and the saving of data types e.g. Arrays.

**Comment by nerdalertdk** [comment]
I Think redis is an okay alternative, I'm looking forward to full redis support

**Comment by m3talstorm** [comment]
A SQL based DB has plenty of performance for Arma

**Comment by Kiina** [comment]
well i haven't done any exact benchmarking for this but it might enable you to log every player action to catch cheaters. so it may be a great addition

**Comment by Torndeco** [comment]
Please stop spamming

-------
Due to way extDB2 is coded for ASYNC + ASYNC Returns
1:<INSERT WHATEVER TASK>  regardless if its MySQL / SQLite / Redis / Logfile / MongoDB
It takes the exact same amount of time todo (as far as arma engine cares)

2:<INSERT WHATEVER TASK> 
Its only when you are retrieving a result, is were it might make a small difference i.e time before result is ready.

0:<INSERT WHATEVER TASK>
Realistic you would only notice performance difference if you used SYNC methods.

----------

So unless you are using SYNC Methods, the choice of backend will have very little to no effect on armaserver performance. 
Its all about how you would like to store data + if you need multiple servers to access the same backend.

**Comment by chris579** [comment]
I asked just because of the better ability to save arrays because of the native data support and not because of performance because it's irrelevant whether you use Mongo or MySQL in case of Arma.

**Comment by m3talstorm** [comment]
I am the development manager over at sawgaming.net, we have a 140 slot Altis Life server with an average of 100 or so players at peak time.

To give you some sort of picture we handle 5000+ database queries (99.9% are async) per 4 hour restart and after 11 days/71 restarts we have collected these stats:

Average query time: 0.027 seconds
Average longest query time: 0.36 seconds

If you are seeing performance issues you need to look at the queries you perform and when, not the dialect you use.

**Comment by chris579** [comment]
Wow, you're a real hero being a "development manager" at a strange Altis Life Server.The first mistake you're making is to use async calls just because of bad performance. Our queries are running in 0.000991821 ms - syncron. You didn't understand my issue: I would have just a MongoDB support especially for arrays just because MySQL didn't supports it natively...

**Comment by m3talstorm** [comment]
"Strange", why is that?

Sync calls are only needed for perhaps 5-7 types of queries, all the others can be performed async so i'm not sure what you are on about.

"0.000991821 ms" ? I think your units are wrong mate ;) Show some evidence of those timing inside a running, decently populated Arma 3 server.

Even if that was seconds, like I said this is an average over 300,000+ queries (both async and sync)

**Comment by Torndeco** [comment]
Wont be adding MongoDB Support, have other goals / projects in mind.
If someone really wants it added send me a pull request with changes...
Poco Library has support for MongoDB
